apiVersion: v2
name: datum
description: A Helm chart to deploy the Datum API server
type: application
version: 0.0.1
appVersion: "0.2.3"
kubeVersion: ">=1.24"

dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 2.14.1
  - name: openfga
    repository: https://openfga.github.io/helm-charts
    tags:
      - openfga
    version: 0.1.35